name: Send CI Run Result

on:
  workflow_run:
    workflows: 
      - CI
    types: 
      - completed

jobs:
  send-webhook-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Action Run Result to Webhook        
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "conclusion": "${{ github.event.workflow_run.conclusion }}" }'
