name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v2

      - name: Install Application Dependencies
        run: npm install

      - name: Building Application Code
        run: npm run build

      - name: Running Unit Tests
        run: npm run test

      - name: Archive Application Code 
        uses: actions/upload-artifact@v2
        with:
          name: application-code
          path: build

      - name: Archive Infrastructure Code 
        uses: actions/upload-artifact@v2
        with:
          name: infrastructure-code
          path: infrastructure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: Production
      
    steps:
      - name: Download the application code
        uses: actions/download-artifact@v2
        with:
          name: application-code
          path: application-code

      - name: Download the infrastructure code
        uses: actions/download-artifact@v2
        with:
          name: infrastructure-code
          path: infrastructure-code

      - name: Install Infrastructure Dependencies
        run: cd infrastructure-code && ls

      - name: Creating / Updating Infrastructure
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'WebsiteStack'
          cdk_args: '--parameters subDomainName=dev-spotify-clone sourceCodeFolder=application-code --require-approval never'
          working_dir: 'infrastructure-code'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: spotify-clone.lyraddigital.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-southeast-2
          SOURCE_DIR: build

      - name: Invalidate index file
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/index.html'
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
