name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Building Code
        run: npm run build

      - name: Running Unit Tests
        run: npm run test

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: spotify-clone.lyraddigital.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-southeast-2
          SOURCE_DIR: build

      - name: Invalidate index file
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            PATHS: '/index.html'
            AWS_REGION: ap-southeast-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
